
services:

  elasticsearch:
    image: elasticsearch:9.4.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  postgres-keycloak:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - kc-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      retries: 10

  postgres-app:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: voltedge
      POSTGRES_USER: voltedge
      POSTGRES_PASSWORD: ${DB_PASSWORD:-voltedge}
    volumes:
      - app-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voltedge"]
      interval: 5s
      retries: 10

  keycloak:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    depends_on:
      postgres-keycloak:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    ports:
      - "8081:8080"
      - "9000:9000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health/ready" ]
      interval: 10s
      retries: 10
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres-app:5432/voltedge
      DB_USERNAME: voltedge
      DB_PASSWORD: ${DB_PASSWORD:-voltedge}
      AUTH_SERVICE_URI: http://keycloak:8080/realms/electronics
      KEYCLOAK_ADMIN_SERVER_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_USERNAME: ${KC_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
      KEYCLOAK_ADMIN_REALM: electronics
      ELASTICSEARCH_URIS: http://elasticsearch:9200
      GROQ_API_KEY: ${GROQ_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-a1sbyp5c}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-439382614736994}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      SPRING_AI_OPENAI_API_KEY: ${GROQ_API_KEY}
      SPRING_AI_VECTORSTORE_QDRANT_HOST: qdrant
      SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      postgres-app:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      qdrant:
        condition: service_started
      keycloak:
        condition: service_healthy
      ollama:
        condition: service_healthy

volumes:
  kc-pgdata:
  es_data:
  qdrant_data:
  app-pgdata:
