spring.application.name=electronics-ecommerce
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=llama-3.3-70b-versatile
spring.ai.openai.chat.temperature=0.3

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=products
spring.ai.vectorstore.qdrant.use-tls=false
spring.ai.vectorstore.qdrant.initialize-schema=true

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

app.chat.max-history-messages=20
app.chat.max-rag-results=5
app.chat.max-product-results=6

stripe.secret-key=${STRIPE_SECRET_KEY:sk_test_51Tk17uK3WD2VtrgnPf2QzhpY4Kl3Qs9ERu7Ft877uFA4DcbfETy8kf6PX5XntHGG5uG2xD2lGJx3tLHXDVxX8rIa00bug1XOqY}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY:pk_test_51Tk17uK3WD2VtrgntAWG06uqZ8DTgCX4vObsoUoKllaF4YXdgGd39gTG0fPuU0zen7ECa53iORPu2MV33U7D5KEv00IAwDOjEr}

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVICE_URI:http://localhost:8081/realms/electronics}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:a1sbyp5c}
cloudinary.api-key=${CLOUDINARY_API_KEY:439382614736994}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

app.keycloak.admin-server-url=${KEYCLOAK_ADMIN_SERVER_URL:http://localhost:8081}
app.keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
app.keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}
app.keycloak.admin-realm=${KEYCLOAK_ADMIN_REALM:electronics}