spring.application.name=electronics-ecommerce
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.model.chat=ollama
spring.ai.model.embedding=none
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.model=${OLLAMA_MODEL:qwen2.5:1.5b}
spring.ai.ollama.chat.temperature=0.1
spring.ai.ollama.chat.think=false
spring.ai.ollama.chat.num-ctx=4096
spring.ai.ollama.chat.num-predict=500
spring.ai.ollama.init.pull-model-strategy=never
spring.ai.retry.max-attempts=2
spring.ai.retry.backoff.initial-interval=200ms
spring.ai.retry.backoff.max-interval=1s
spring.ai.retry.backoff.multiplier=2

stripe.secret-key=${STRIPE_SECRET_KEY:sk_test_51Tk17uK3WD2VtrgnPf2QzhpY4Kl3Qs9ERu7Ft877uFA4DcbfETy8kf6PX5XntHGG5uG2xD2lGJx3tLHXDVxX8rIa00bug1XOqY}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY:pk_test_51Tk17uK3WD2VtrgntAWG06uqZ8DTgCX4vObsoUoKllaF4YXdgGd39gTG0fPuU0zen7ECa53iORPu2MV33U7D5KEv00IAwDOjEr}

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVICE_URI:http://localhost:8081/realms/electronics}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:a1sbyp5c}
cloudinary.api-key=${CLOUDINARY_API_KEY:439382614736994}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

app.keycloak.admin-server-url=${KEYCLOAK_ADMIN_SERVER_URL:http://localhost:8081}
app.keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
app.keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}
app.keycloak.admin-realm=${KEYCLOAK_ADMIN_REALM:electronics}